Detail
GeoWerkstatt/interlis-model-browser pull request #44
Opened 2022-08-18 12:38 UTC by MiraGeowerkstatt

#12

2022-08-18 13:58 UTC, patrickackermann requested changes

2022-08-18 13:58 UTC, patrickackermann commented on src/ClientApp/src/components/Detail.js
> +    const response = await fetch(model.uri);
REQ: Überprüfen ob der response ok ist.

2022-08-18 13:58 UTC, patrickackermann commented on src/ClientApp/src/components/Detail.js
> +    getModelPreview(model);
Q: Müssen die Funktionsaufrufe nicht awaited werden?

2022-08-19 07:30 UTC, MiraGeowerkstatt commented on src/ClientApp/src/components/Detail.js
> +    getModelPreview(model);
Stimmt man könnte sich ein re-render sparen, wenn man das getModel abwartet.

2022-08-19 10:14 UTC, patrickackermann requested changes

2022-08-19 11:14 UTC, patrickackermann approved these changes

2022-08-19 11:16 UTC, danjov approved these changes

2022-08-22 07:28 UTC, merged